apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-to-inet-frontend
spec:
  podSelector:
    matchLabels:
      role: frontend
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.233.64.0/18
              - 192.168.99.0/24
#              - 10.233.90.0/24
#              - 10.233.96.0/24