apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-for-frontend
spec:
  podSelector:
    matchLabels:
      role: frontend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 10.233.96.112/32
  egress:
    - to:
        - ipBlock:
            cidr: 10.233.96.112/32