apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-for-backend
spec:
  podSelector:
    matchLabels:
      role: backend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - ipBlock:
          cidr: 10.233.90.148/32
  egress:
    - to:
      - ipBlock:
          cidr: 10.233.90.148/32
