apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
      protocol: TCP
    - containerPort: 443
      protocol: TCP
    volumeMounts:
    - name: certs
      mountPath: "/etc/nginx/ssl"
      readOnly: true
    envFrom:
    - secretRef:
        name: mysecret
  volumes:
  - name: certs
    secret:
      secretName: domain-cert
