apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  ports:
  # Порт сетевого балансировщика, на котором будут обслуживаться пользовательские запросы.
  - port: 80
    name: http
    # Порт контейнера, на котором доступно приложение.
    targetPort: 8080
  # Метки селектора, использованные в шаблоне подов при создании объекта Deployment.
  selector:
    app.kubernetes.io/instance: my-phpmyadmin
  type: LoadBalancer
